- name: "Create EC2 Instances and Add R53 Records"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    subnet_id: "subnet-03f08bdcb40e9e725"
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-02aa5635332d4841f"
    instances:
      - "mysql"
      - "frontend"
      - "backend"
    zone: "khanishkcosmetics.store"
    region: "us-east-1"

  tasks:
    - name: ansible to install boto3 and botocore
      ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3.9
    - name: "Launch EC2 Instances"
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: "creating r53 records"
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"
        type: A
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
        ttl: 1
      loop: "{{ ec2_instances.results }}"
    - name: "creating r53 records"
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
        ttl: 1
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"