- name: "Create EC2 Instances and Add R53 Records"
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    subnet_id: "subnet-03f08bdcb40e9e725"
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-02aa5635332d4841f"
    instances:
      - "mysql"
      - "frontend"
      - "backend"
    zone_id: "Z10192312YWL9AAQ8B02Q"
    region: "us-east-1"

  tasks:

    - name: "Launch EC2 Instances"
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        wait: yes
        region: "{{ region }}"
      loop: "{{ instances }}"
      register: ec2_instances
