- name: "configuring the mysql server"
  hosts: mysql
  become: yes
  vars:
    login_host: "mysql.khanishkcosmetics.store"
    login_password: "ExpenseApp@1"
    login_user: "root"
  tasks:
    - name: ansible to install pymysql
      ansible.builtin.pip:
        name:
        - PyMySQL
        executable: pip3.9

    - name: "installing mysql servers"
      ansible.builtin.package:
        name: mysql-server
        state: present
    
    - name: "starting and enabling mysql-server"
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    
    - name: "checking the root password is      setup/ not"
      community.mysql.mysql_db:
        login_host: "{{ login_host }}"
        login_password: "{{ login_password }}"
        login_user: "{{ login_user }}"
      ignore_errors: true
      register: mysql_info

    - name: "printing mysql info"
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"

    - name: "setting root password if not setup"
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
      when: mysql_info.failed is true


