- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    login_host: "mysql.khanishkcosmetics.store"
    login_password: "ExpenseApp@1"
  tasks:
  # Here we are installing mysql server in mysql.khanishkcostmeics.store which is created from demo.yaml
  - name: install mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present
  # Starting mysql server it's neccessary when u install a particular service and enabling also 
  - name: starting mysqlserver
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  #Acutally directly connecting to mysql server and setting/ changing root password , 1st check whether the login host is there 
  - name: "connecting to mysql server"
    community.mysql.mysql_info:
      login_user: root
      login_host: "{{ login_host }}"
      login_password: "{{ login_password }}"
    ignore_errors: true
    register: mysql_info
  
  - name: "checking it is connected or not"
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
  
  - name: "setup mysql root password"
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_password }}"
    when: mysql_info.failed is true

