name: "installing mysql server"
ansible.builtin.package:
  name: "mysql-server"
  state: present

name: "starting and enabling mysql service"
ansible.builtin.service:
  name: "mysqld"
  state: started
  enabled: yes
